services:
  - type: web
    name: smart-company-backend
    env: node
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: smart-company-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://managementsystem-44ae6.web.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: smart-company-db
    databaseName: smart_company_db
    user: smart_company_user
    region: frankfurt
    plan: free
